In [23]:
from sklearn.feature_selection import f_regression
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv('files/1.02.+Multiple+linear+regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [9]:
x, y = data[['SAT', 'Rand 1,2,3']], data['GPA']
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

### The first array corresponds to the f-statistics for each feature. The second, to the p-values

In [10]:
p_values = f_regression(x, y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [11]:
p_values.round(3)

array([0.   , 0.676])